# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title count 
#' @description count the number of rejected
#' @param sigma the variance of the normal distribution 
#' @param x0 the initial value
#' @param N number of trials
#' @return a vector
#' @export
Metropolis <- function(sigma, x0, N) {
    .Call('_StatComp20024_Metropolis', PACKAGE = 'StatComp20024', sigma, x0, N)
}

#' @title count 
#' @description count the number of rejected
#' @param sigma the variance of the normal distribution 
#' @param x0 the initial value
#' @param N number of trials
#' @return a vector
#' @export
rwMetropolis <- function(sigma, x0, N) {
    .Call('_StatComp20024_rwMetropolis', PACKAGE = 'StatComp20024', sigma, x0, N)
}

